name: todos_api
description: Interface and models for todos api
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.1.0"

dependencies:
  equatable: ^2.0.3
  json_annotation: ^4.5.0
  meta: ^1.7.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  test: ^1.19.2
  very_good_analysis: ^3.0.0
